.github/workflows/ci.yml, publish_unit_test_results.py
=> Support `pull_request` and `pull_request_target` events

.github/workflows/ci.yml, README.md, action.yml, publish_unit_test_results.py, test/test_publish.py
=> Hide all but latest comment

README.md, publish_unit_test_results.py
=> Add support to schedule event

README.md, publish_unit_test_results.py, test/test_get_commit_sha.py
Does not limit the action to an explicit list of events but supports any event and handles all known deviations like `pull_request` properly.
=> Supports any event

action.yml
=> Add missing inputs to action yaml

README.md, action.yml, publish/__init__.py, publish/publisher.py, publish_unit_test_results.py, test/test_publish.py, test/test_publisher.py
Adds list of all tests and skipped tests to check run.
Test files are sorted alphabetically in the test failure annotation.
=> Add test list annotations

publish/__init__.py, publish/publisher.py, publish_unit_test_results.py, test/test_action_script.py, test/test_publish.py, test/test_publisher.py
=> Test action settings

junit/__init__.py, test/files/xunit.xml, test/test_junit.py
=> Don't insist on class *and* test name

README.md, action.yml, composite/action.yml, publish/publisher.py, publish_unit_test_results.py, test/test_action_script.py, test/test_publisher.py
=> Allow to disable comparison to earlier commits

README.md, action.yml, composite/action.yml, python/publish_unit_test_results.py, python/test/__init__.py, python/test/test_action_script.py
Reverts EnricoMi/publish-unit-test-result-action#121
=> Revert "Improve files option, support multiline, excludes and default value"

README.md, action.yml, composite/action.yml, python/publish_unit_test_results.py, python/test/__init__.py, python/test/test_action_script.py
Fixes bug #124 introduced by #121, which was merged into master and later reverted (#125).
=> Improve files option, support multiline, excludes and default value (part II)

.github/workflows/unit-test-results.yml, README.md
Here is an example run for a PR from a fork: https://github.com/jgiannuzzi/publish-unit-test-result-action/runs/2667822522?check_suite_focus=true
=> Simplify unit test results for pull requests by using GitHub CLI

.github/workflows/ci-cd.yml
Runs the action on given test files to end-to-end-test those files.
=> Integration test with unit test files

README.md, python/publish/__init__.py, python/test/test_publish.py, python/test/test_publisher.py
=> Add link to README.md and tooltip to icons in result post

python/publish/junit.py, python/requirements.txt, python/test/test_junit.py
Issue https://github.com/weiwei/junitparser/issues/71 has been resolved, upgrading junitparser version and removing workaorund.
=> Move to junitparser==2.2.0, removing workaround solved in new version

python/publish/__init__.py, python/test/test_publish.py
=> Do not truncate durations and deltas over 60h (%), introduce days (d)

README.md
=> Add required permissions to README.md

.github/ISSUE_TEMPLATE/issue-template.md
Add issue template to ask for useful input when issue is created.
=> Add issue template

.github/workflows/ci-cd.yml
Scans the docker image for vulnerabilities, adds them to Github Security and posts annotations.
=> Scan docker image for vulnerabilities

Dockerfile
Upgrades the base python alpine image to latest 3.8, which fixes CVE vulnerabilities. Fixes #216.
=> Upgrade docker base image to Python 3.8 alpine

python/publish/__init__.py, python/publish/publisher.py, python/test/files/unsupported-unicode.xml, python/test/test_publish.py, python/test/test_publisher.py
Fixes #250. Likely related to #212.
=> Restrict unicode sent to Github API

python/publish/github_action.py
=> Make sure TextIOWrapper.reconfigure exists

python/test/test_action_yml.py, python/test/test_cicd_yml.py, python/test/test_junit.py, python/test/test_publish.py, python/test/test_readme_md.py
As discussed in #266 I'm separating refactor on tests from original PR
=> Use absolute paths to files from tests

.github/workflows/ci-cd.yml, python/publish/__init__.py, python/test/test_publish.py
=> Re-arrange layout without runs

.github/workflows/ci-cd.yml, README.md, action.yml, composite/action.yml, python/publish/publisher.py, python/publish_test_results.py, python/test/test_action_script.py, python/test/test_publisher.py
=> Add action_fail option

.github/workflows/ci-cd.yml, README.md, action.yml, composite/action.yml, python/publish/junit.py, python/publish/nunit.py, python/publish/publisher.py, python/publish/trx.py, python/publish/xunit.py, python/publish_test_results.py, python/test/test_action_script.py, python/test/test_publisher.py
Parses XML with `huge_tree` set: https://lxml.de/api/lxml.etree.XMLParser-class.html
Fixes #399.
=> Allow to parse XML with huge tree option

python/publish/nunit.py, python/publish/trx.py, python/publish/xunit.py
Restricts what the XSLT files can do.
=> Restrict XSLT permissions

python/publish/xslt/nunit-to-junit.xslt, python/publish/xslt/trx-to-junit.xslt
Make typing of number explicit in XSLT.
=> Add explicit number typing to xslt

python/publish/xslt/trx-to-junit.xslt
=> Add index to look up UnitTest by id

python/publish/publisher.py, python/publish_test_results.py, python/test/test_action_script.py, python/test/test_publisher.py
=> Allow to publish job summary for pull_request event on fork

.github/workflows/test-results.yml, README.md
=> Use workflow download action instead of script

README.md, action.yml, composite/action.yml, python/publish_test_results.py, python/test/test_action_script.py
=> Document using relative paths

python/publish_test_results.py, python/test/test_action_script.py
Inconclusive conclusion is actually called "neutral" internally.
=> Fix failing on no files

.github/workflows/ci-cd.yml, .github/workflows/publish.yml, .github/workflows/test-os.yml
Requires rework of matrix strategy in `test-os.yaml`.
=> Add macOS 14 to CI

python/requirements-3.10.txt, python/requirements-3.11.txt, python/requirements-3.12.txt, python/requirements-3.7.txt, python/requirements-3.8.txt, python/requirements-3.9.txt, python/requirements-post-3.7.txt
Fixing
- https://github.com/EnricoMi/publish-unit-test-result-action/security/code-scanning/108
- https://github.com/EnricoMi/publish-unit-test-result-action/security/code-scanning/105
- https://github.com/EnricoMi/publish-unit-test-result-action/security/code-scanning/102
- https://github.com/EnricoMi/publish-unit-test-result-action/security/code-scanning/87
=> Upgrade dependencies

.github/workflows/publish.yml, README.md, action.yml, composite/action.yml, linux/action.yml, macos/action.yml, python/publish/publisher.py, python/publish_test_results.py, python/test/test_action_script.py, python/test/test_github.py, python/test/test_publisher.py, windows/action.yml, windows/bash/action.yml
=> Add option to verify SSL/TLS connection

python/publish/junit.py, python/test/files/junit-xml/empty-system-out-err.annotations, python/test/files/junit-xml/empty-system-out-err.junit-xml, python/test/files/junit-xml/empty-system-out-err.results, python/test/files/junit-xml/empty-system-out-err.results.json, python/test/files/junit-xml/empty-system-out-err.xml, python/test/test_action_script.py
=> Fix for empty `<system-out>` and `<system-err>`
