EnricoMi/publish-unit-test-result-action

publish_unit_test_results.py
test/files/minimal-attributes.xml
test/files/no-attributes.xml
test/test_publish.py

This makes the action work with result files that miss any or all attributes.
Fixes #24

Work with no attributes in xml result files

---

publish_unit_test_results.py
test/test_publish.py

Replace :heavy_multiplication_x: with :x:

---

publish_unit_test_results.py
test/test_publish.py

This makes the `-` align well with the `+` and `±`.

Add whitespaces to minus sign

---

README.md
publish_unit_test_results.py

This PR allows hard coded issue comment title `Unit Test Results` to be changed when `COMMENT_TITLE` env var is defined.

Add COMMENT_TITLE env var for issue comment title

---

README.md
action.yml
publish_unit_test_results.py

Add option comment_on_pr

---

.github/workflows/ci.yml
publish_unit_test_results.py
test/test_publish.py

Null `raw_details` are not allowed, just removing `raw_content` from the `dict` when `None`.

Fix nil raw details

---

README.md
publish_unit_test_results.py

Manually triggered event are not supported: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#manual-events.
If the `workflow_dispatch` event name is used, the action will raise this error: `RuntimeError("event '{}' is not supported".format(event))`.
Add support for `workflow_dispatch` event name.

Add support for workflow_dispatch event name

---

publish/publisher.py
test/test_publisher.py

A commit can be part of multiple PRs in a single repo when on PR is closed and another is created. In this situation, the action picks the open PR. If none is open, none is used to publish a comment. If there is only one PR, the comment is published there no matter the state.

Handle multiple PRs per commit

---

README.md
action.yml
publish/__init__.py
publish_unit_test_results.py
test/test_publisher.py

The test list annotations (all tests, skipped tests) are only published on default branch. This is configurable.

Test list annotations only on default branch

---

publish/__init__.py
test/test_publish.py

Uses colapsable `<details>` sections for list of changed tests. Fixes #83.

Moves test list in comments into details section

---

publish/publisher.py
publish_unit_test_results.py
test/test_action_script.py
test/test_publisher.py

Use GITHUB_GRAPHQL_URL

---

.github/workflows/ci-cd.yml
.github/workflows/unit-test-results.yml
README.md

Improves documentation to address #95. Also makes this project's CI workflow work with dependabot branches.

Make CI/CD workflow work with dependabot branches

---

.github/workflows/ci-cd.yml

Since we run the action from docker image, publishing test results from branch does not work any more as it also picks up the released pre-built image. This temporarily switches the `action.yaml` to the Dockerfile, so the action is built from branch source.

Really use action from this branch

---

.github/workflows/ci-cd.yml
publish/publisher.py
publish_unit_test_results.py
requirements.txt
test/requirements.txt
test/test_github.py

Post requests and 5xx errors are not retried. Tests with a mock REST endpoint the retry behaviour of the GitHub client. Fixes #110.

Improve GitHub client retry behaviour

---

junit/__init__.py
test/files/testcase-in-testcase.xml
test/test_publish.py

This seems to be allowed, at least Jenkins supports that: https://llg.cubic.org/docs/junit/
Fixes #107.

Handle testcase tags inside testcase tags

---

README.md
action.yml
composite/action.yml
python/publish_unit_test_results.py
python/test/__init__.py
python/test/test_action_script.py

Fixes #119 and adds more features around `files:` option.

Improve files option, support multiline, excludes and default value

---

.github/workflows/ci-cd.yml
README.md
composite/action.yml
python/requirements.txt
python/test/test_action_script.py

To simplify the composite action and improve startup speed, lets remove using a virtual environment. This action can easily isolated from other actions that use the runner's Python environment by running it in a dedicated workflow. For the discussion, see #123.

Remove venv and pip upgrade from composite action

---

python/publish_unit_test_results.py

Looks like the deprecation warning is also printed when `comment_on_pr` is not used:
Warning: Option comment_on_pr is deprecated! Instead, use option "comment_mode" with values "off", "create new", or "update last".

Remove unnecessary deprecation warning

---

python/publish_unit_test_results.py
python/test/test_action_script.py
python/test/test_action_yml.py
python/test/test_cicd_yml.py

The pull request title and body, as well as commit messages are part of the `event.json` file. That file is written with UTF8 encoding and read by the action. The action uses the system's default encoding when reading that JSON file, which is `cp1252` on Windows.
Fixes #129.

Handle non-ASCII characters in event file

---

python/publish/__init__.py
python/publish/publisher.py
python/test/test_publish.py
python/test/test_publisher.py

Creating test list annotations handles cases where lists exceed 64kB. Lists are then split into multiple annotations (chunks). These annotation lists are read by the action running on later commits. However, reading multiple chunks is not implemented:
```
publish - ERROR - Found multiple annotation with all tests in check run 2668777005
```
Changes:

Handle multiple test list chunks

---

action.yml
composite/action.yml

Hello
The `github_token` input parameter has a default value and is not required.
It makes my `vscode` yell at me:

The github_token input has a default value and is not required

---

README.md
python/publish/__init__.py
python/publish/junit.py
python/publish/unittestresults.py
python/test/files/disabled.xml
python/test/test_junit.py
python/test/test_unittestresults.py

Fixes #143 partially by including disabled tests in skipped tests. Before, disabled tests where not recognized as such at all and considered passed tests. Since junitparser packages does not support disabled test cases either, introducing this notion here is a bit hacky. Once the package supported that, changes from this PR should be tidied up.

Count disabled tests as skipped

---

python/publish_unit_test_results.py
python/test/test_github.py

This explicitly implements #150 as those exceptions still occur even with throttled API calls.

Retry all 403 responses

---

.github/workflows/ci-cd.yml

Ubuntu 16.04 is deprecated, removed it and added some specific Windows versions.

Update test OSes

---

python/publish/publisher.py

The action has some debug messages that access `totalCount`, which might call out to the GitHub API. This is not needed when logging level is not DEBUG, so we better skip that. This might make #170 go away but does not fix it as we do not want to see that issue when logging at DEBUG level.

Avoid API calls for debug message when disabled

---

python/publish/__init__.py
python/publish/publisher.py
python/test/test_publisher.py

Check runs for a commit include workflow job names. If those happen to have the same name as the check run of the result, then the action cannot find a single check run of the base commit. This filters check runs further.

Pick best check run

---

python/publish/publisher.py
python/test/test_publisher.py

When summary is `None` the new method `get_check_run_from_list` fails checking for contained string. This is fixed and tested.

Fixing issue when summary is None

---

python/publish/publisher.py
python/test/test_publisher.py

Avoids the action to compare a commit with itself in a pull request comment (see #148).

Do not compare commit to itself

---

python/publish/publisher.py
python/test/test_publisher.py

Earlier (#176) we decided not to compare to itself, but it is better not to publish a PR comment at all as it would not contain change stats and would replace earlier comments that might contain those stats.

Do not publish a pr comment when we would compare the commit to itself

---

python/publish/junit.py
python/test/files/with-xml-entities.xml
python/test/files/xml-entities-in-names.xml
python/test/test_junit.py

The junitparser lib provides access to the JUnit XML files. Some string values are HTML encoded, e.g. `TestCase.name` and `TestCase.classname`.
This change accesses those string values through the element's attributes to get pure, non-escaped text data. Can be reverted once this behaviour is fixed upstream.
See https://github.com/weiwei/junitparser/issues/71. Fixes #184.

Use unescaped strings from TestCase

---

python/publish_unit_test_results.py
python/test/test_action_script.py

Composite action calls into the Docker image and sets all supported inputs. Here, originally unset inputs are set as empty strings:
https://github.com/EnricoMi/publish-unit-test-result-action/blob/fbe06cdc30e0d61a17e2a41d579239cf8e1c6841/composite/action.yml#L115-L138
The `event_file` arguments turns out to be the only effected by this, all other have defaults for `None` and empty strings. This PR turns empty input strings into proper `None`s. This makes the "running-on-a-fork-PR" check in `main` work for the composite action (where `settings.event_file` is not `None` but an empty string):
https://github.com/EnricoMi/publish-unit-test-result-action/blob/fbe06cdc30e0d61a17e2a41d579239cf8e1c6841/python/publish_unit_test_results.py#L63-L71
As @BlasiusSecundus showed in …

Treat empty input strings as None

---

python/publish/retry.py
python/test/test_github.py

Don't rely on exponential backoff when rate limit is exceeded but wait until rate limit reset happens. This is related to #222.

Retry exceeded rate limit after reset timestamp

---

.github/workflows/ci-cd.yml
python/publish/retry.py
python/test/test_github.py

Fixes #225.
Reproduced in https://github.com/EnricoMi/python/runs/5324173294?check_suite_focus=true#step:5:179:
```
2022-02-25 06:01:15 +1030 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-02-25 06:01:15 +1030 - publish-unit-test-results -  INFO - Response body indicates retry-able error: api rate limit exceeded for installation id 5425010.
2022-02-25 06:01:15 +1030 - publish-unit-test-results - DEBUG - Response header contains X-RateLimit-Limit=30
2022-02-25 06:01:15 +1030 - publish-unit-test-results - DEBUG - Response header contains X-RateLimit-Remaining=0
2022-02-25 06:01:15 +1030 - publish-unit-test-results - DEBUG - Response header contains X-RateLimit-Reset=1645731119
2022-02-25 06:01:15 +1030 - publish-unit-test-results - DEBUG - …
```

Make reset timestamps UTC, test with specific timezone

---

python/publish/unittestresults.py
python/test/files/no-cases-but-tests.xml
python/test/test_publish.py

XML files without `<testcase>` tags still contain the number of tests, skipped tests and failures in the `<testsuites>` tags. The action then reports those numbers as "runs" while tests are all 0 (first seen in #231):
This fixes this. The "tests" line contains the numbers and the "run" line is removed, as there are no individual test case information.

Testsuites without testcases

---

python/publish_unit_test_results.py
python/test/test_action_script.py

The function prints a warning when something other than true/false is used. This fixes #194.

Add get_bool_var for parsing boolean inputs

---

python/publish_unit_test_results.py
python/test/test_action_script.py

- fixes regexp in is_alpha, extends testing
- fixes the way TEST_CHANGES_LIMIT is parsed
- harmonize parsing numbers in get_settings
- remove _default from test names, test all cases for each option
- compact options raising exceptions, use more loops and sub-tests
- move unknown value tests into specific option tests

Fix and rework settings tests

---

python/publish/__init__.py
python/publish/publisher.py
python/test/test_publish.py
python/test/test_publisher.py

Complements #251:
- Restrict unicode of test names for PR comment
- Restrict unicode in all annotation text fields

Restrict unicode in all text fields populated with user input

---

composite/action.yml

Currently the composite action does not work on self-hosted Windows runners because the version check does not pass.
The version string is printed with an upper case P, at least for python 3.9. Not sure about older versions so I adjusted the check to work with both.
```shell
$ python -V
Python 3.9.12
```

Fix python interpreter detection

---

python/publish/github_action.py
python/test/test_github_action.py

This adds support for [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) to GithubAction class.
If environment variable is not set, or file is not writeable, a warning about this is written to GitHub Actions.
Re-doing ##269.

 Add support for environment files to GithubAction

---

.github/workflows/ci-cd.yml
.github/workflows/test-results.yml
README.md
action.yml
composite/action.yml
python/test/test_action_yml.py
python/test/test_cicd_yml.py

Remove mention of 'unit', only non-breaking changes
- Does not rename the action in the marketplace
- Does not rename the action name in `uses:` clause
- Does not rename the default value of check_name option

Remove unit term

---

.github/workflows/ci-cd.yml
README.md
action.yml
composite/action.yml
python/publish/publisher.py
python/publish_unit_test_results.py
python/test/test_action_script.py
python/test/test_action_yml.py
python/test/test_publisher.py

This allows to support multiple test result file formats without the need to detect the format. There are multiple XML variants but usually, only a single is format is used and fully known to the user.

Rename files arg to junit_files, deprecate files

---

python/publish/junit.py
python/publish/progress.py
python/publish/retry.py
python/publish_unit_test_results.py
python/requirements.txt
python/test/test_progress.py

Logs the number of files to read and their size, the available memory, and logs progress every 10s.
Fixes #304.

Log file sizes and free mem

---

python/publish/publisher.py
python/test/test_publisher.py

Add check-run HTML URL to JSON output.

---

.github/workflows/ci-cd.yml
python/test/files/nunit/nunit3/jenkins/NUnit-sec1752-file.exception
python/test/files/nunit/nunit3/jenkins/NUnit-sec1752-https.exception
python/test/test_action_script.py
python/test/test_junit.py

Tests on macOS with Python 3.10 fail after upgrading lxml. Investigating and fixing issue.

Fix lxml upgrade

---

python/publish/github_action.py
python/publish/publisher.py
python/publish_test_results.py
python/test/test_github_action.py
python/test/test_publisher.py

- add notice, echo and output env file to GHA
- turn echo on in debug mode
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use GHA env file to set output

---

.github/workflows/ci-cd.yml
python/test/test_github_action.py

This should fix the issue with [this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
[Relevent GH Issue](https://github.com/EnricoMi/publish-unit-test-result-action/issues/363)

Use GHA env file to set output in CI

---

.github/workflows/ci-cd.yml
README.md
action.yml
composite/action.yml
python/publish/publisher.py
python/publish/unittestresults.py
python/publish_test_results.py
python/test/test_action_script.py
python/test/test_publish.py
python/test/test_publisher.py
python/test/test_unittestresults.py

Adds the ability to optionally write out all of the individual unit test results to json file.
Intended to resolve #365

Add option to write test cases to JSON file

---

python/publish/publisher.py
python/test/test_publisher.py

Fix regexes to detect chunked annotations

---

python/publish/publisher.py
python/test/test_publisher.py

The Publisher::publish_comment method calls some properties that were not defined on UnitTestRunResults.

Fix UnitTestRunResults interface to be compatible with UnitTestRunDeltaResults

---

python/publish/publisher.py
python/test/test_publisher.py

Reverts commit 763fc579cccadd02d67a247f4372a6dcb7088b0d and falls back to the commit's pull requests when the event does not provide a PR.
Fixes #437.

Publish comment on pull request of event, or of commit otherwise

---

.github/workflows/ci-cd.yml
README.md
action.yml
composite/action.yml
python/publish/publisher.py
python/publish_test_results.py
python/test/test_action_script.py
python/test/test_publisher.py

In one of my org projects, I can not use `GITHUB_TOKEN` for API rate limiting issues. So I used GitHub App to authenticate this action.
But the issue in this approach is the action creates a new comment for each run which bloats the PR (I run 3 workflows with this action for each commit, for 10 commits, it creates 30 comments).
In this PR, we are adding support for optionally providing `actor_name`, which will be used to find the correct comment to be replaced. 
I am not totally sure about the naming of this new variable. Please suggest if this needs to be changed. 
And thanks for this awesome action.

Add actor name option

---

.github/workflows/ci-cd.yml
python/publish/dart.py

... and another typo.
[_source_](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/spelling.yml)
There were two typos excluding `python/test/files/*` files.
In `python/test/files` there are 1044 additional typos.
What to do now?

Fix spelling issues

---

python/publish_test_results.py

Drop excessive output from when `action_fail` is enabled.
As a job with many such steps (different kinds of tests) becomes very verbose and hard to get an overview of.
Here's an example of such output:
>Configuration requires this action to fail (action_fail=True, action_fail_on_inconclusive=False).
i.e:
>![Skärmavbild 2023-10-06 kl  14 53 18](https://github.com/EnricoMi/publish-unit-test-result-action/assets/62675/66e0699f-b913-495e-9f9b-4eb109195d31)

Drop excessive output from `action_fail`

---

.github/workflows/ci-cd.yml

Allow the action to run on self-hosted ARM64 workers, compatible with AWS Graviton ARM instances.

Publish ARM images

---

python/publish/__init__.py
python/publish/publisher.py
python/test/test_publish.py
python/test/test_publisher.py

Handle incomplete / none JSON elements

---

.github/actions/test/action.yml
.github/workflows/badges.yml
.github/workflows/ci-cd.yml
.github/workflows/codeql.yml
.github/workflows/publish.yml
.github/workflows/test-os.yml
composite/action.yml
python/requirements-direct.txt
python/requirements.txt

fix #498
Hi @EnricoMi,
I just discovered this project.
This PR upgrades the `checkout` action to release v4. I also used the [`upgrade-pip-packages.sh`](https://github.com/EnricoMi/publish-unit-test-result-action/blob/d826f852b6b65be05c9bcc086cfc7e181255d464/.github/upgrade-pip-packages.sh) script to upgrade the pip dependencies.
I hope that this PR might be helpful. I'd be grateful if you would consider sharing your feedback on this below.

Upgrade CI and Python dependencies

---

python/publish/publisher.py
python/publish/unittestresults.py
python/test/test_junit.py
python/test/test_publish.py
python/test/test_publisher.py
python/test/test_unittestresults.py

- add before_stats to JSON
- add suite_details to stats_with_delta
- improve formatted stats_with_delta (error delta)
Fixes #554.
Supersedes #555.
Includes #567, rebase after that has been merged.

Publish JSON even when `check_run` is false

---

.github/actions/test/action.yml
.github/upgrade-pip-packages.sh
.github/workflows/ci-cd.yml
Dockerfile
README.md
composite/action.yml
linux/action.yml
macos/action.yml
python/requirements-3.10.txt
python/requirements-3.11.txt
python/requirements-3.12.txt
python/requirements-3.7.txt
python/requirements-3.8.txt
python/requirements-3.9.txt
python/requirements-direct.txt
python/requirements-post-3.7.txt
python/requirements.txt
python/test/constraints.txt
tox.ini
windows/action.yml
windows/bash/action.yml

Support Python 3.12

---

windows/bash/action.yml

In #585 the python bin got unquoted, leading to #586:
https://github.com/EnricoMi/publish-unit-test-result-action/blob/466ab0b314344b3e139d89f65e65980baedf587a/windows/bash/action.yml#L179
Fixes #586.

Quote python bin in windows bash action

---

windows/action.yml

Looks like the double quotes do not work on all Windows runners.
Fixes #602

Avoid escaped quotes in Windows PowerShell action

---

.github/workflows/ci-cd.yml
.github/workflows/publish.yml

Jobs fail once `*.dockerbuild` got uploaded:
- https://github.com/docker/build-push-action/issues/1167.
- https://github.com/EnricoMi/publish-unit-test-result-action/actions/runs/9876224564/job/27275276162#step:6:12

CI: Do not upload docker build record

---

python/publish/__init__.py

In some cases annotation path or message could be `None`, which is not allowed by the CheckRun API.
Fixes #620.

Add default path and message for parse error and suite output annotations

---

.github/actions/test/action.yml
.github/workflows/ci-cd.yml
composite/action.yml
linux/action.yml
macos/action.yml
python/requirements-3.10.txt
python/requirements-3.11.txt
python/requirements-3.12.txt
python/requirements-3.13.txt
python/requirements-3.7.txt
python/requirements-3.8.txt
python/requirements-3.9.txt
python/requirements-post-3.7.txt
python/requirements.txt
windows/action.yml
windows/bash/action.yml

Add Python 3.13

---

composite/action.yml

This applies #587 to the deprecated composite action. Fixes the deprecated composite action for hosts where Python is installed in paths containing spaces, Windows is most likely affected.

Quote `$PYTHON_BIN` in deprecated composite action

---

.github/workflows/publish.yml
README.md

This adds example workflow YAML to provide an example of how to replace the composite action with OS-specific actions in a multi-OS job. Further mentions the Windows Bash action at the to of the `README.md`.

Add composite replacement to `README.md`

---

python/test/test_junit.py

This small PR resolves the regex library warnings:
```python
python/test/test_junit.py:224: DeprecationWarning: 'count' is passed as positional argument
```

Resolve regex library warnings

---

.github/workflows/check-action-typing.yml
README.md
action-types.yml
composite/action-types.yml
linux/action-types.yml
macos/action-types.yml
python/test/test_action_yml.py
windows/action-types.yml
windows/bash/action-types.yml

I would like to see your action first-class supported by https://github.com/typesafegithub/github-workflows-kt, a Kotlin DSL to write GitHub Action workflows.
The project came up with ways to reduce operational load when keeping the library's action wrappers in sync with actions' inputs and outputs.
The solutions include onboarding https://github.com/typesafegithub/github-actions-typing.
It is as easy as adding an extra YAML file to your repository root, and (optionally) adding a simple GitHub workflow that validates this new file.
Thanks to this, the code generator in the Kotlin DSL can fetch typing info provided by you instead of them, which has a number of benefits.
It has no negative effects on current action consumers, they continue to use the action via regular GitHub API, as if the …

Add action typing
